export default[
    {
       country_code:"AF",
       label:"Afghanistan"
    },
    {
       country_code:"AX",
       label:"\u00c5land Islands"
    },
    {
       country_code:"AL",
       label:"Albania"
    },
    {
       country_code:"DZ",
       label:"Algeria"
    },
    {
       country_code:"AS",
       label:"American Samoa"
    },
    {
       country_code:"AD",
       label:"Andorra"
    },
    {
       country_code:"AO",
       label:"Angola"
    },
    {
       country_code:"AI",
       label:"Anguilla"
    },
    {
       country_code:"AQ",
       label:"Antarctica"
    },
    {
       country_code:"AG",
       label:"Antigua and Barbuda"
    },
    {
       country_code:"AR",
       label:"Argentina"
    },
    {
       country_code:"AM",
       label:"Armenia"
    },
    {
       country_code:"AW",
       label:"Aruba"
    },
    {
       country_code:"AU",
       label:"Australia"
    },
    {
       country_code:"AT",
       label:"Austria"
    },
    {
       country_code:"AZ",
       label:"Azerbaijan"
    },
    {
       country_code:"BS",
       label:"Bahamas"
    },
    {
       country_code:"BH",
       label:"Bahrain"
    },
    {
       country_code:"BD",
       label:"Bangladesh"
    },
    {
       country_code:"BB",
       label:"Barbados"
    },
    {
       country_code:"BY",
       label:"Belarus"
    },
    {
       country_code:"BE",
       label:"Belgium"
    },
    {
       country_code:"BZ",
       label:"Belize"
    },
    {
       country_code:"BJ",
       label:"Benin"
    },
    {
       country_code:"BM",
       label:"Bermuda"
    },
    {
       country_code:"BT",
       label:"Bhutan"
    },
    {
       country_code:"BO",
       label:"Bolivia, Plurinational State of"
    },
    {
       country_code:"BQ",
       label:"Bonaire, Sint Eustatius and Saba"
    },
    {
       country_code:"BA",
       label:"Bosnia and Herzegovina"
    },
    {
       country_code:"BW",
       label:"Botswana"
    },
    {
       country_code:"BV",
       label:"Bouvet Island"
    },
    {
       country_code:"BR",
       label:"Brazil"
    },
    {
       country_code:"IO",
       label:"British Indian Ocean Territory"
    },
    {
       country_code:"BN",
       label:"Brunei Darussalam"
    },
    {
       country_code:"BG",
       label:"Bulgaria"
    },
    {
       country_code:"BF",
       label:"Burkina Faso"
    },
    {
       country_code:"BI",
       label:"Burundi"
    },
    {
       country_code:"KH",
       label:"Cambodia"
    },
    {
       country_code:"CM",
       label:"Cameroon"
    },
    {
       country_code:"CA",
       label:"Canada"
    },
    {
       country_code:"CV",
       label:"Cape Verde"
    },
    {
       country_code:"KY",
       label:"Cayman Islands"
    },
    {
       country_code:"CF",
       label:"Central African Republic"
    },
    {
       country_code:"TD",
       label:"Chad"
    },
    {
       country_code:"CL",
       label:"Chile"
    },
    {
       country_code:"CN",
       label:"China"
    },
    {
       country_code:"CX",
       label:"Christmas Island"
    },
    {
       country_code:"CC",
       label:"Cocos (Keeling) Islands"
    },
    {
       country_code:"CO",
       label:"Colombia"
    },
    {
       country_code:"KM",
       label:"Comoros"
    },
    {
       country_code:"CG",
       label:"Congo"
    },
    {
       country_code:"CD",
       label:"Congo, the Democratic Republic of the"
    },
    {
       country_code:"CK",
       label:"Cook Islands"
    },
    {
       country_code:"CR",
       label:"Costa Rica"
    },
    {
       country_code:"CI",
       label:"C\u00f4te d'Ivoire"
    },
    {
       country_code:"HR",
       label:"Croatia"
    },
    {
       country_code:"CU",
       label:"Cuba"
    },
    {
       country_code:"CW",
       label:"Cura\u00e7ao"
    },
    {
       country_code:"CY",
       label:"Cyprus"
    },
    {
       country_code:"CZ",
       label:"Czech Republic"
    },
    {
       country_code:"DK",
       label:"Denmark"
    },
    {
       country_code:"DJ",
       label:"Djibouti"
    },
    {
       country_code:"DM",
       label:"Dominica"
    },
    {
       country_code:"DO",
       label:"Dominican Republic"
    },
    {
       country_code:"EC",
       label:"Ecuador"
    },
    {
       country_code:"EG",
       label:"Egypt"
    },
    {
       country_code:"SV",
       label:"El Salvador"
    },
    {
       country_code:"GQ",
       label:"Equatorial Guinea"
    },
    {
       country_code:"ER",
       label:"Eritrea"
    },
    {
       country_code:"EE",
       label:"Estonia"
    },
    {
       country_code:"ET",
       label:"Ethiopia"
    },
    {
       country_code:"FK",
       label:"Falkland Islands (Malvinas)"
    },
    {
       country_code:"FO",
       label:"Faroe Islands"
    },
    {
       country_code:"FJ",
       label:"Fiji"
    },
    {
       country_code:"FI",
       label:"Finland"
    },
    {
       country_code:"FR",
       label:"France"
    },
    {
       country_code:"GF",
       label:"French Guiana"
    },
    {
       country_code:"PF",
       label:"French Polynesia"
    },
    {
       country_code:"TF",
       label:"French Southern Territories"
    },
    {
       country_code:"GA",
       label:"Gabon"
    },
    {
       country_code:"GM",
       label:"Gambia"
    },
    {
       country_code:"GE",
       label:"Georgia"
    },
    {
       country_code:"DE",
       label:"Germany"
    },
    {
       country_code:"GH",
       label:"Ghana"
    },
    {
       country_code:"GI",
       label:"Gibraltar"
    },
    {
       country_code:"GR",
       label:"Greece"
    },
    {
       country_code:"GL",
       label:"Greenland"
    },
    {
       country_code:"GD",
       label:"Grenada"
    },
    {
       country_code:"GP",
       label:"Guadeloupe"
    },
    {
       country_code:"GU",
       label:"Guam"
    },
    {
       country_code:"GT",
       label:"Guatemala"
    },
    {
       country_code:"GG",
       label:"Guernsey"
    },
    {
       country_code:"GN",
       label:"Guinea"
    },
    {
       country_code:"GW",
       label:"Guinea-Bissau"
    },
    {
       country_code:"GY",
       label:"Guyana"
    },
    {
       country_code:"HT",
       label:"Haiti"
    },
    {
       country_code:"HM",
       label:"Heard Island and McDonald Islands"
    },
    {
       country_code:"VA",
       label:"Holy See (Vatican City State)"
    },
    {
       country_code:"HN",
       label:"Honduras"
    },
    {
       country_code:"HK",
       label:"Hong Kong"
    },
    {
       country_code:"HU",
       label:"Hungary"
    },
    {
       country_code:"IS",
       label:"Iceland"
    },
    {
       country_code:"IN",
       label:"India"
    },
    {
       country_code:"ID",
       label:"Indonesia"
    },
    {
       country_code:"IR",
       label:"Iran, Islamic Republic of"
    },
    {
       country_code:"IQ",
       label:"Iraq"
    },
    {
       country_code:"IE",
       label:"Ireland"
    },
    {
       country_code:"IM",
       label:"Isle of Man"
    },
    {
       country_code:"IL",
       label:"Israel"
    },
    {
       country_code:"IT",
       label:"Italy"
    },
    {
       country_code:"JM",
       label:"Jamaica"
    },
    {
       country_code:"JP",
       label:"Japan"
    },
    {
       country_code:"JE",
       label:"Jersey"
    },
    {
       country_code:"JO",
       label:"Jordan"
    },
    {
       country_code:"KZ",
       label:"Kazakhstan"
    },
    {
       country_code:"KE",
       label:"Kenya"
    },
    {
       country_code:"KI",
       label:"Kiribati"
    },
    {
       country_code:"KP",
       label:"Korea, Democratic People's Republic of"
    },
    {
       country_code:"KR",
       label:"Korea, Republic of"
    },
    {
       country_code:"KW",
       label:"Kuwait"
    },
    {
       country_code:"KG",
       label:"Kyrgyzstan"
    },
    {
       country_code:"LA",
       label:"Lao People's Democratic Republic"
    },
    {
       country_code:"LV",
       label:"Latvia"
    },
    {
       country_code:"LB",
       label:"Lebanon"
    },
    {
       country_code:"LS",
       label:"Lesotho"
    },
    {
       country_code:"LR",
       label:"Liberia"
    },
    {
       country_code:"LY",
       label:"Libya"
    },
    {
       country_code:"LI",
       label:"Liechtenstein"
    },
    {
       country_code:"LT",
       label:"Lithuania"
    },
    {
       country_code:"LU",
       label:"Luxembourg"
    },
    {
       country_code:"MO",
       label:"Macao"
    },
    {
       country_code:"MK",
       label:"Macedonia, the Former Yugoslav Republic of"
    },
    {
       country_code:"MG",
       label:"Madagascar"
    },
    {
       country_code:"MW",
       label:"Malawi"
    },
    {
       country_code:"MY",
       label:"Malaysia"
    },
    {
       country_code:"MV",
       label:"Maldives"
    },
    {
       country_code:"ML",
       label:"Mali"
    },
    {
       country_code:"MT",
       label:"Malta"
    },
    {
       country_code:"MH",
       label:"Marshall Islands"
    },
    {
       country_code:"MQ",
       label:"Martinique"
    },
    {
       country_code:"MR",
       label:"Mauritania"
    },
    {
       country_code:"MU",
       label:"Mauritius"
    },
    {
       country_code:"YT",
       label:"Mayotte"
    },
    {
       country_code:"MX",
       label:"Mexico"
    },
    {
       country_code:"FM",
       label:"Micronesia, Federated States of"
    },
    {
       country_code:"MD",
       label:"Moldova, Republic of"
    },
    {
       country_code:"MC",
       label:"Monaco"
    },
    {
       country_code:"MN",
       label:"Mongolia"
    },
    {
       country_code:"ME",
       label:"Montenegro"
    },
    {
       country_code:"MS",
       label:"Montserrat"
    },
    {
       country_code:"MA",
       label:"Morocco"
    },
    {
       country_code:"MZ",
       label:"Mozambique"
    },
    {
       country_code:"MM",
       label:"Myanmar"
    },
    {
       country_code:"NA",
       label:"Namibia"
    },
    {
       country_code:"NR",
       label:"Nauru"
    },
    {
       country_code:"NP",
       label:"Nepal"
    },
    {
       country_code:"NL",
       label:"Netherlands"
    },
    {
       country_code:"NC",
       label:"New Caledonia"
    },
    {
       country_code:"NZ",
       label:"New Zealand"
    },
    {
       country_code:"NI",
       label:"Nicaragua"
    },
    {
       country_code:"NE",
       label:"Niger"
    },
    {
       country_code:"NG",
       label:"Nigeria"
    },
    {
       country_code:"NU",
       label:"Niue"
    },
    {
       country_code:"NF",
       label:"Norfolk Island"
    },
    {
       country_code:"MP",
       label:"Northern Mariana Islands"
    },
    {
       country_code:"NO",
       label:"Norway"
    },
    {
       country_code:"OM",
       label:"Oman"
    },
    {
       country_code:"PK",
       label:"Pakistan"
    },
    {
       country_code:"PW",
       label:"Palau"
    },
    {
       country_code:"PS",
       label:"Palestine, State of"
    },
    {
       country_code:"PA",
       label:"Panama"
    },
    {
       country_code:"PG",
       label:"Papua New Guinea"
    },
    {
       country_code:"PY",
       label:"Paraguay"
    },
    {
       country_code:"PE",
       label:"Peru"
    },
    {
       country_code:"PH",
       label:"Philippines"
    },
    {
       country_code:"PN",
       label:"Pitcairn"
    },
    {
       country_code:"PL",
       label:"Poland"
    },
    {
       country_code:"PT",
       label:"Portugal"
    },
    {
       country_code:"PR",
       label:"Puerto Rico"
    },
    {
       country_code:"QA",
       label:"Qatar"
    },
    {
       country_code:"RE",
       label:"R\u00e9union"
    },
    {
       country_code:"RO",
       label:"Romania"
    },
    {
       country_code:"RU",
       label:"Russian Federation"
    },
    {
       country_code:"RW",
       label:"Rwanda"
    },
    {
       country_code:"BL",
       label:"Saint Barth\u00e9lemy"
    },
    {
       country_code:"SH",
       label:"Saint Helena, Ascension and Tristan da Cunha"
    },
    {
       country_code:"KN",
       label:"Saint Kitts and Nevis"
    },
    {
       country_code:"LC",
       label:"Saint Lucia"
    },
    {
       country_code:"MF",
       label:"Saint Martin (French part)"
    },
    {
       country_code:"PM",
       label:"Saint Pierre and Miquelon"
    },
    {
       country_code:"VC",
       label:"Saint Vincent and the Grenadines"
    },
    {
       country_code:"WS",
       label:"Samoa"
    },
    {
       country_code:"SM",
       label:"San Marino"
    },
    {
       country_code:"ST",
       label:"Sao Tome and Principe"
    },
    {
       country_code:"SA",
       label:"Saudi Arabia"
    },
    {
       country_code:"SN",
       label:"Senegal"
    },
    {
       country_code:"RS",
       label:"Serbia"
    },
    {
       country_code:"SC",
       label:"Seychelles"
    },
    {
       country_code:"SL",
       label:"Sierra Leone"
    },
    {
       country_code:"SG",
       label:"Singapore"
    },
    {
       country_code:"SX",
       label:"Sint Maarten (Dutch part)"
    },
    {
       country_code:"SK",
       label:"Slovakia"
    },
    {
       country_code:"SI",
       label:"Slovenia"
    },
    {
       country_code:"SB",
       label:"Solomon Islands"
    },
    {
       country_code:"SO",
       label:"Somalia"
    },
    {
       country_code:"ZA",
       label:"South Africa"
    },
    {
       country_code:"GS",
       label:"South Georgia and the South Sandwich Islands"
    },
    {
       country_code:"SS",
       label:"South Sudan"
    },
    {
       country_code:"ES",
       label:"Spain"
    },
    {
       country_code:"LK",
       label:"Sri Lanka"
    },
    {
       country_code:"SD",
       label:"Sudan"
    },
    {
       country_code:"SR",
       label:"Suriname"
    },
    {
       country_code:"SJ",
       label:"Svalbard and Jan Mayen"
    },
    {
       country_code:"SZ",
       label:"Swaziland"
    },
    {
       country_code:"SE",
       label:"Sweden"
    },
    {
       country_code:"CH",
       label:"Switzerland"
    },
    {
       country_code:"SY",
       label:"Syrian Arab Republic"
    },
    {
       country_code:"TW",
       label:"Taiwan, Province of China"
    },
    {
       country_code:"TJ",
       label:"Tajikistan"
    },
    {
       country_code:"TZ",
       label:"Tanzania, United Republic of"
    },
    {
       country_code:"TH",
       label:"Thailand"
    },
    {
       country_code:"TL",
       label:"Timor-Leste"
    },
    {
       country_code:"TG",
       label:"Togo"
    },
    {
       country_code:"TK",
       label:"Tokelau"
    },
    {
       country_code:"TO",
       label:"Tonga"
    },
    {
       country_code:"TT",
       label:"Trinidad and Tobago"
    },
    {
       country_code:"TN",
       label:"Tunisia"
    },
    {
       country_code:"TR",
       label:"Turkey"
    },
    {
       country_code:"TM",
       label:"Turkmenistan"
    },
    {
       country_code:"TC",
       label:"Turks and Caicos Islands"
    },
    {
       country_code:"TV",
       label:"Tuvalu"
    },
    {
       country_code:"UG",
       label:"Uganda"
    },
    {
       country_code:"UA",
       label:"Ukraine"
    },
    {
       country_code:"AE",
       label:"United Arab Emirates"
    },
    {
       country_code:"GB",
       label:"United Kingdom"
    },
    {
       country_code:"US",
       label:"United States"
    },
    {
       country_code:"UM",
       label:"United States Minor Outlying Islands"
    },
    {
       country_code:"UY",
       label:"Uruguay"
    },
    {
       country_code:"UZ",
       label:"Uzbekistan"
    },
    {
       country_code:"VU",
       label:"Vanuatu"
    },
    {
       country_code:"VE",
       label:"Venezuela, Bolivarian Republic of"
    },
    {
       country_code:"VN",
       label:"Viet Nam"
    },
    {
       country_code:"VG",
       label:"Virgin Islands, British"
    },
    {
       country_code:"VI",
       label:"Virgin Islands, U.S."
    },
    {
       country_code:"WF",
       label:"Wallis and Futuna"
    },
    {
       country_code:"EH",
       label:"Western Sahara"
    },
    {
       country_code:"YE",
       label:"Yemen"
    },
    {
       country_code:"ZM",
       label:"Zambia"
    },
    {
       country_code:"ZW",
       label:"Zimbabwe"
    }
 ]