"""empty message

Revision ID: 0a92428e2535
Revises: 668ebe34c88c
Create Date: 2022-03-27 13:35:38.007223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a92428e2535'
down_revision = '668ebe34c88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'is_favourite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'is_favourite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
