"""empty message

Revision ID: 35e5c544ecfe
Revises: b14c29015254
Create Date: 2022-03-28 19:36:47.495179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e5c544ecfe'
down_revision = 'b14c29015254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trip_city_key', 'trip', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trip_city_key', 'trip', ['city'])
    # ### end Alembic commands ###
