"""empty message

Revision ID: 6317ea0e4049
Revises: b5a4af95e241
Create Date: 2022-03-24 17:30:25.090042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6317ea0e4049'
down_revision = 'b5a4af95e241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=220),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=220),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
