"""empty message

Revision ID: b14c29015254
Revises: 0a92428e2535
Create Date: 2022-03-28 17:01:01.033550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14c29015254'
down_revision = '0a92428e2535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'is_favourite',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'is_favourite',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
